### ISSUE TITLE
Premium warbonds should have their pass cost as their first page unlock cost

### ISSUE THREAD

**Issue by Stonemercy** [helldivers-2/json#21]
https://github.com/helldivers-2/json/blob/e57d9c4b7a4c770853a34fa341017acc8e3b48ce/warbonds/cutting_edge.json#L1-L5

e.g. Cutting Edge costs 1000 SC

(personal opinion)

**Comment by chatterchats** [comment]
Hm, not the worst idea, and would kinda make is_premium in the warbonds.json a little redundant I think. @dealloc Thoughts?

**Comment by dealloc** [comment]
> Hm, not the worst idea, and would kinda make is_premium in the warbonds.json a little redundant I think. @dealloc Thoughts?

It would, I'd just add the super credit cost and that'd suffice in my opinion

**Comment by chatterchats** [comment]
I’ll work on the PR here in a bit to make the changes
