### ISSUE TITLE
Armour Penetration needs to be centralised on one term

### ISSUE THREAD

**Issue by Stonemercy** [helldivers-2/json#22]
https://github.com/helldivers-2/json/blob/e57d9c4b7a4c770853a34fa341017acc8e3b48ce/items/weapons/traits.json#L3-L5

**Comment by dealloc** [comment]
What's the advantage of merging all three?
Wouldn't we lose information?

**Comment by Stonemercy** [comment]
Sorry I couldnt think of the right words at the time

Just recommending we use either "penetrating" or "penetration" not both

Now that I think about it this didn't really need an issue but 🤷🏻

**Comment by dealloc** [comment]
Ohh, no that makes sense!
We should definitely keep this somewhat consistent.

@chatterchats this one you think you could pick up?
