### ISSUE TITLE
[BUG]: Incorrect slots for some armours

### ISSUE THREAD

**Issue by devpoole2907** [helldivers-2/json#31]
### Faulty File Path & Name

json/items/armor/armor.json

### Request information

Incorrect slots for some armours, example is Cresting Honor and Foesmasher capes are listed as 0/"head"

"1180159923": {
		"name": "Foesmasher",
		"description": "Durable, waterproof, and thermally-lined, surplus units of this cape are favored by domestic campers, to make tents.",
		"type": 1,
		"slot": 0,
		"armor_rating": 100,
		"speed": 100,
		"stamina_regen": 100,
		"passive": 0
	},

"1404455928": {
		"name": "Cresting Honor",
		"description": "An entirely olive-green cape with minimal markings or insignia.",
		"type": 1,
		"slot": 0,
		"armor_rating": 100,
		"speed": 100,
		"stamina_regen": 100,
		"passive": 0
	}

### What is expected?

Cresting Honor and Foesmasher are cloaks/capes - their slot should be 1/"cloak"

### What is actually happening?

```json
These capes are marked as 0/"head"
```

### Any additional comments?

I think there's a couple more capes incorrectly listed, if you need me to help finding them I'm happy to have a further look when I've got some time, cheers

**Comment by chatterchats** [comment]
Looked into this more, seems it was an error across the entire armors.json. Was able to rectify and just waiting on review to merge the fix, apologies for that!

Fixed in #32
