### ISSUE TITLE
[BUG]: L'estrade sector name incorrect

### ISSUE THREAD

**Issue by paulleonartcalvo** [helldivers-2/json#33]
### Faulty File Path & Name

https://api.helldivers2.dev/api/v1/planets/259

### Request information

Requesting for planet Omicron as an example

### What is expected?

should be "L'estrade"

![image](https://github.com/helldivers-2/api/assets/93534747/a0c6407d-7b0a-4050-a6ea-c232ad368b6a)

### What is actually happening?

```json
It is showing "Le'strade"
```

**Comment by dealloc** [comment]
oops, looks like those sector names got mapped wrong.
@chatterchats can I get your eyes on this one?

**Comment by dealloc** [comment]
never mind, looks like #34 already handles this, Chats can review the PR
