### ISSUE TITLE
[BUG]: Update stats to patch 01.000.300

### ISSUE THREAD

**Issue by Stonemercy** [helldivers-2/json#35]
### Faulty File Path & Name

items\weapons\primary,secondary.json

### Request information

[Patch 01.000.300](https://steamcommunity.com/games/553850/announcements/detail/4169846298204053637) updated the damage numbers on many weapons as well as changing some types to Energy

### What is expected?

Correct information

### What is actually happening?

```json
Slightly incorrect information
```

### Any additional comments?

Hope I did this right!

#36 should fix most/all of the issues

**Comment by dealloc** [comment]
@Stonemercy great work, really appreciate it!
