### ISSUE TITLE
[FEATURE]: Include icons/textures where relevant

### ISSUE THREAD

**Issue by ROBOT0-VT** [helldivers-2/json#44]
### What problem is solved?

Developers who use this repository will need an alternate source to retrieve static image data such as booster and planet icons, which would not be updated alongside this repository

### What is the solution?

#EITHER:

Include an `icon` parameter containing the serialised image data

#OR:

Have a folder with the appropriate icons as a subfolder to the one containing the relevant *.json file

### What value does this add?

Easier access for developers making gui-based tools (web applications etc)

**Comment by dealloc** [comment]
While I absolutely see the merit, I feel like including copyrighted image data might be pushing legal boundaries I'm not entirely comfortable pushing.
@chatterchats thoughts?

**Comment by chatterchats** [comment]
100% Including copyrighted material is something I'm not comfortable doing. However, should a community pack of custom icons to represent things be made that are copyleft without infringing on HD2's IP wouldn't be the worst idea, should it be made however

**Comment by dealloc** [comment]
we're going to play it safe, I feel including actual textures from the game would be pushing legal limits I'd rather not
