### ISSUE TITLE
[BUG]: Fort Justice has the wrong biome in planets/planets.json

### ISSUE THREAD

**Issue by CrosswaveOmega** [helldivers-2/json#57]
### Faulty File Path & Name

/planets/planets.json

### Request information

Fort Justice has the wrong biome listed.  It should have the ethereal biome, not the tundra biome.

You can verify this by checking https://data.helldivers.io/?settings=generated_planet_data&index=22

### What is expected?

https://data.helldivers.io/?settings=generated_planet_data&index=22

"This world teems with ethereal, boundless, and peculiar plant life that spreads silent and uninterrupted across its entire surface."

This is the description for the ethereal biome, however tundra is listed for Fort Justice.

"tundra": {
		"name": "Tundra",
		"description": "A perennially chilly climate has allowed short, colourful shrubs to flourish across this planet's surface."
	},

### What is actually happening?

```json
"21": {
		"name": "Fort Justice",
		"sector": "Kelvin",
		"biome": "tundra",
		"environmentals": [
			"none"
		],
		"names": {
			"en-US": "FORT JUSTICE",
			"en-GB": "FORT JUSTICE",
			"pt-BR": "FORTE DA JUSTIÇA",
			"de-DE": "FORT JUSTICE",
			"es-ES": "FUERTE JUSTICIA",
			"fr-FR": "FORT JUSTICE",
			"it-IT": "FORT JUSTICE",
			"ja-JP": "フォート・ジャスティス",
			"ko-KO": "포트 저스티스",
			"ms-MY": "FUERTE DE LA JUSTICIA",
			"pl-PL": "FORT SPRAWIEDLIWOŚCI",
			"pt-PT": "FORT JUSTICE",
			"ru-RU": "ФОРТ ПРАВОСУДИЯ",
			"zh-Hans": "正义堡",
			"zh-Hant": "正義堡"
		}
	},


should be

"21": {
		"name": "Fort Justice",
		"sector": "Kelvin",
		"biome": "ethereal",
		"environmentals": [
			"none"
		],
		"names": {
			"en-US": "FORT JUSTICE",
			"en-GB": "FORT JUSTICE",
			"pt-BR": "FORTE DA JUSTIÇA",
			"de-DE": "FORT JUSTICE",
			"es-ES": "FUERTE JUSTICIA",
			"fr-FR": "FORT JUSTICE",
			"it-IT": "FORT JUSTICE",
			"ja-JP": "フォート・ジャスティス",
			"ko-KO": "포트 저스티스",
			"ms-MY": "FUERTE DE LA JUSTICIA",
			"pl-PL": "FORT SPRAWIEDLIWOŚCI",
			"pt-PT": "FORT JUSTICE",
			"ru-RU": "ФОРТ ПРАВОСУДИЯ",
			"zh-Hans": "正义堡",
			"zh-Hant": "正義堡"
		}
	},
```

**Comment by dealloc** [comment]
@chatterchats is this one you can pick up?
